# Use a imagem oficial do Node.js
FROM node:22-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copia os ficheiros de dependência para cache
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código da aplicação
COPY . .

# Expõe a porta que o Express está a usar
EXPOSE 3000

# Comando para iniciar a aplicação Node.js
CMD [ "node", "server.js" ]