# Usa imagem leve e recente do Node
FROM node:22-alpine

# Cria e define o diretório de trabalho
WORKDIR /usr/src/app

# Copia dependências para cache
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia o código da aplicação
COPY . .

# Expõe a porta interna que o Express está a usar
EXPOSE 3000

# Inicia a aplicação
CMD [ "node", "server.js" ]